codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

  ignore:
    - "tests/"
    - "docs/"
    - "stpy/__pycache__/"
    - "stpy/codes/__pycache__/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
